sonar.projectKey=sushil-oss_ReactTodoUIMonolith_41fb7513-5689-4c57-8a92-1a37e99a2000
sonar.projectName=ReactTodoUIMonolith
sonar.organization=sushil-oss
sonar.sources=.
sonar.exclusions=node_modules/**,build/**,dist/**
